---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tst-0008
  namespace: tenant-a
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tst-0008
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tst-0008
    spec:
      containers:
        - name: container
          image: 'polinux/stress-ng:latest'
          args:
            - '--cpu'
            - '8'
            - '--io'
            - '4'
            - '--vm'
            - '2'
            - '--vm-bytes'
            - 128M
            - '--timeout'
            - 300s
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600